# Generated by Django 5.1.4 on 2024-12-14 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_company_id_company_company_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="Company_id",
            new_name="company_id",
        ),
    ]
